# Deploy last pushed Jupyter Book docs (_build/) to the docs branch for GH pages

name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  push-docs-dir:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Push docs dir
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: "_build/html"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
