# Deploy last pushed Jupyter Book docs (_build/) to the docs branch for GH pages

name: Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  push-docs-dir:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Build Jupyter Book
        run: |
          jupyter-book build .

      - name: Add CNAME
        run: |
          pwd && ls && echo "paddy.pfiers.net" > CNAME && ls

      - name: Push docs dir
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: "_build/html"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
